name: Print On Push

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  print_on_push:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print a message
        run: |
          echo "New commit detected on branch ${{ github.ref }}!"
          echo "Commit details:"
          git log -n 1 --format="%h %an %s"
